### ISSUE TITLE
Homey 2.0 | Since beta update retrieve no data

### ISSUE THREAD

**Issue by Sjalabert** [rickardp/homey-prometheus-exporter#8] opened 2018-12-07 07:11 UTC
I have updated Homey to version 2.0. Now Prometheus no longer receives data. All values are 0. Restarting the tool makes no difference. Or is prometheu.io no longer supported with version 2.0?

**Comment by rickardp** [comment] 2018-12-07 10:21
I have not tested the Prometheus exporter with Homey 2.0. Unfortunately I only own one Homey, and it's the one running my home, so I am reluctant to upgrade it a beta version since there is no downgrade path.

I will check compatibility once 2.0 is stable and I have upgraded.

Or if there are any brave ones out there on 2.0 beta that can tell pinpoint what has changed, feel free to send a PR.

**Comment by rickardp** [comment] 2018-12-07 11:14
I have now received some stacktraces from 2.0 beta and it definitely looks like something has changed. I will see if I can start ahead to have something ready around the time 2.0 is released.

**Comment by Sjalabert** [comment] 2018-12-07 14:45
Great, When I can help you. Let me know.

**Comment by nerdtechse** [comment] 2019-01-13 00:12
Hi! First of all great app just love to make my homey work with grafana! :)

Is there any progress on making it work for 2.0? Its just a couple o day away from getting released.

**Comment by rickardp** [comment] 2019-01-13 12:38
I have had a quick look at it, but I have no 2.0 device to test on. Last time I enabled experimental updates I had to do a full factory reset to get back, which I am reluctant to do on my “production” Homey. I could perhaps push the dev branch if there is anyone brave enough out there to test it.

**Comment by meden199** [comment] 2019-01-13 14:05
I'am running the latest RC Firmware 2.0.0

**Comment by nerdtechse** [comment] 2019-01-15 12:09
I´m willing to test the dev branch!

**Comment by rickardp** [comment] 2019-01-15 14:11
Athom released the 2.0 firmware. I will test some on this first, then I'll release an alpha version.

**Comment by rjgough** [comment] 2019-01-16 12:56
Any ETA on the alpha version ? I’m blind without any data ! :)!

**Comment by GreyEarl** [comment] 2019-01-16 21:37
Until now I realized Prometheus was not working after updating! Totally blind as well! My grafana page is still superior than the app.

**Comment by rickardp** [comment] 2019-01-16 22:16
I have fixed a few issues that caused the app to misbehave on 2.0 and I have now started testing it on my newly upgraded Homey. The changes are pushed to the "alpha" branch. I have not verified that anything but the most basic stats work. Any help testing is appreciated.

**Comment by nerdtechse** [comment] 2019-01-16 22:42
Works here.. But stops at 
# HELP homey_presence User presence
# TYPE homey_presence gauge

**Comment by rickardp** [comment] 2019-01-17 09:41
Yes, presence is work in progress. It currently provides no data as this is simply not implemented yet.

**Comment by rjgough** [comment] 2019-01-17 09:42
Ok super but this prevents device metrics too.. the output data just halts at this point

**Comment by rickardp** [comment] 2019-01-17 10:40
@rjgough That is probably because this is the last metric. If device metrics is not working that is another problem. I think I saw the device metrics yesterday, but I will investigate some more. Do you think you can post the output from the metrics page?

**Comment by rjgough** [comment] 2019-01-17 11:49
> @rjgough That is probably because this is the last metric (and it happens to have no values). If device metrics is not working that is another problem. I think I saw the device metrics yesterday, but I will investigate some more. Do you think you can post the output from the metrics page?

Sure

https://gist.github.com/rjgough/582ff811317aa241a3e95dbff18232d3

**Comment by rickardp** [comment] 2019-01-17 22:24
I just had another look at it and it seems device state is reported differently. The devices are detected (as can be seen in that the z-wave stats work), but they no lounger report state

**Comment by lauer** [comment] 2019-01-17 22:34
Okay. Can I do anything to help you?

**Comment by rickardp** [comment] 2019-01-17 23:34
@lauer It would sure help to test the current solution out and see if it works. I’ll run it overnight and see what Grafana thinks in the morning. The metrics page seems to report device on/off etc now, but in Grafana discrepancies will be more visible.

**Comment by lauer** [comment] 2019-01-18 18:32
I have just installed your updates from tonight, and it seems to work - I will let you know if I find any problems.

**Comment by rjgough** [comment] 2019-01-18 18:51
Works here too, Grafana seems to be populating nicely

**Comment by nerdtechse** [comment] 2019-01-19 13:06
@rickardp  your a damn good and fast coder!  Everything works great here!

**Comment by nerdtechse** [comment] 2019-01-19 18:33
And the log is from the new version from beta branch.

**Comment by rickardp** [comment] 2019-01-19 18:47
@nerdtechse Thanks for reporting! I know of the MaxListenersExceededWarning and I have not fully investigated, but it seems like some arbitrary limit of 10 set somewhere in Node. I need to fix it, but it’s just a warning and doesn’t break anything.

As for the app kill, it just says “Connection has been lost, exiting...”. Is this reproducible when you do “athom app install” ?

**Comment by nerdtechse** [comment] 2019-01-19 20:03
Could be that homey kills it.. But in the app i cant se if its running och not like before with the computer app. 

No network issue has a ping graph against homey and that doesnt show any anomalities.. Yes its connection refused.

**Comment by rickardp** [comment] 2019-01-20 00:17
@nerdtechse Just to confirm:
`curl http://homeyip:80` gives a response
`curl http://homeyip:9414/metrics` gives "Connection refused" ?

And running the app with "athom app run" has it working for a few hours, then just terminating, while "athom app install" never works at all?

Is the issue still there after you reboot the Homey?

**Comment by nerdtechse** [comment] 2019-01-20 10:44
1) Redirecting to https://go.athom.com/homey-root
2) Gives Connection refused

"Athom app run" does the same as "athom app install" just connection refused.. 2 days ago ive got it to run for some hours but then it just stopped and i havent got it to work even with a couple of reboots.

**Comment by rickardp** [comment] 2019-01-21 07:38
@nerdtechse I asked on Slack for instructions on how to get the system logs and the disappointing answer is that there appears to be no way to get them, as the Homey is locked down.

When doing “athom app run”, it fails directly now? Can you please post the app logs for this case?

**Comment by nerdtechse** [comment] 2019-01-21 08:55
@rickardp The log i attached earlier is the same as now. All thats in the log happends in a 2-3 seconds.

**Comment by Sjalabert** [comment] 2019-01-21 14:47
Strange, I've installed prometheus V0.2.1 with CLI. I've see him in the homey app and I can reach him by website. But get no data. What did I wrong.

**Comment by rickardp** [comment] 2019-01-21 17:45
@Sjalabert so you can browse to the /metrics page, but Prometheus is not picking up the data?

You can check the Prometheus web UI (port 9090) and see if the target scrape fails. Hopefully there’s an error message if this is the case.

**Comment by rickardp** [comment] 2019-01-21 17:55
Beta app published!

**Comment by nerdtechse** [comment] 2019-01-21 19:10
@rickardp same problem after install from Appstore sent a log with number 2da7fb5c-957e-4e51-9658-786f578674ec

**Comment by rickardp** [comment] 2019-01-21 19:58
@nerdtechse Thanks! I saw the report and this actually contains some form of error at least.

    a: network timeout at: http://localhost:80/api/manager/system/storage
        at Timeout._onTimeout (/node_modules/athom-api/dist/index.js:1:315053)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)

I will ask on slack or the forum about this, as I have no idea what it means.

**Comment by nerdtechse** [comment] 2019-01-21 21:33
I found something.. If i take out the part from the app about storage it runs like it should! .. Can it be that it take to long time to give a answer about storage and that breaks it?. It take a long time even in the iphone app to get the info.

**Comment by rickardp** [comment] 2019-01-22 00:41
Interesting. I could wrap that part in a try/catch, but it should really not kill the app, only produce a warning (but still bad since it will prevent other scanners). I suspect this timeout triggers something in the system that kills the app, but it doesn’t hurt to try.

The storage page reloads in about 1-2 seconds for me. I take it yours is significantly slower? Maybe you got a ton of files in there that some app created?

**Comment by rickardp** [comment] 2019-01-22 18:15
New beta submitted with the changes above. Should be out tomorrow.

**Comment by GreyEarl** [comment] 2019-01-22 20:51
@rickardp, what is your PayPal address? I couldn't find it anywhere..

**Comment by rickardp** [comment] 2019-01-22 21:35
@GreyEarl There should be a donate link on the app page that’s supposed to go to my paypal. https://apps.athom.com/app/io.prometheus

**Comment by rickardp** [comment] 2019-01-23 18:40
New beta published. Should fix some minor issues that some users reported (e.g. with polling).

**Comment by rickardp** [comment] 2019-01-24 18:34
Closing this issue now, as there are no reported issues left. If you encounter problems, please open a new issue specifically for the problem.

The app is now officially supporting Homey 2.0.

**Closed by rickardp** 2019-01-24 18:34 UTC
Labels: bug
