### ISSUE TITLE
3 times higher deviceupdate Call Rate since 0.3.3

### ISSUE THREAD

**Issue by josefzahner** [rickardp/homey-prometheus-exporter#27] opened 2022-09-14 06:26 UTC
It's me again, sorry. I've used the 0.3.3 test version and switched over to the normal 0.3.3 version. As you can see it has had a huge impact on the call rate. I've about factor 3 more for deviceupdate and registerdevice.
![Screenshot 2022-09-14 at 08 22 03](https://user-images.githubusercontent.com/33521474/190075653-683584b6-48f1-462d-aeb7-8d8a96201d83.png)

Is that expected behavior? Interestingly It hasn't had much of an impact on the CPU...?

**Comment by rickardp** [comment] 2022-09-14 17:54
The call rate for poll should be higher than previous versions since it is now split into several smaller functions, but nothing was changed with the device update. Moreover, 0.3.3 test and live are exactly the same, it's just an option in the apps dashboard which to take live.

Can you see which device is driving the call rate?

**Comment by josefzahner** [comment] 2022-09-14 19:07
More or less all devices are going crazy... I've inserted below the overall graph, but as I have that much devices is hard to read, so I picked some of them. But more or less all devices show the same factor of more call rates?

![Screenshot 2022-09-14 at 21 06 18](https://user-images.githubusercontent.com/33521474/190241362-e5073204-a788-4e94-aa33-654cda339672.png)

![Screenshot 2022-09-14 at 21 04 40](https://user-images.githubusercontent.com/33521474/190241399-f69f623a-3d88-454e-8e15-07b2ad4564b3.png)

![Screenshot 2022-09-14 at 21 04 56](https://user-images.githubusercontent.com/33521474/190241402-66b7f06e-18f0-497f-99a2-2e156e51ad43.png)

![Screenshot 2022-09-14 at 21 05 08](https://user-images.githubusercontent.com/33521474/190241405-9fdf26cf-3ffd-43eb-a37b-e8f5409d2c37.png)

**Comment by rickardp** [comment] 2022-09-16 17:56
What happens if you restart the app?

**Comment by josefzahner** [comment] 2022-09-16 20:17
I’ve already that multiple times. Always the same like in the pictures above

**Comment by rickardp** [comment] 2023-04-05 22:57
Is this still an issue? Can you check if it happens on 0.5.0?

**Comment by rickardp** [comment] 2023-04-06 22:08
Closing this for now as no work is planned for now. If able to reproduce on v0.5.0 or later please reopen.

**Closed by rickardp** 2023-04-06 22:08 UTC
